Update README.md - DropDown
atapas/markdown-cheatsheet pull request #12
Opened 2022-09-18 18:09 UTC by AmenaNajeeb

Created Number 22. DropDown

The users will be able to see the detailed message only when they click on the summary.

2022-09-19 01:43 UTC, atapas reviewed
@AmenaNajeeb thanks for putting it. Can you please create an issue for the PR so that we have a track of changes?

2022-09-19 05:54 UTC, AmenaNajeeb commented
Yes Sir.

On Mon, Sep 19, 2022, 07:13 Tapas Adhikary ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> @AmenaNajeeb <https://github.com/AmenaNajeeb> thanks for putting it. Can
> you please create an issue for the PR so that we have a track of changes?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/atapas/markdown-cheatsheet/pull/12#pullrequestreview-1111632228>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHU5SOGGFRBZ4CEBV5G6BBTV67AMTANCNFSM6AAAAAAQPRKTNA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-19 15:27 UTC, atapas requested changes
@AmenaNajeeb Thanks for putting this PR. A few comments.

2022-09-19 15:27 UTC, atapas commented on README.md
> +<details open>
@AmenaNajeeb Can we please show the example without `open`?

2022-09-19 15:27 UTC, atapas commented on README.md
> +
Here we can add a sentence explaining what `summary` and `details` and talk about the `open` attribute.

2022-09-19 16:31 UTC, AmenaNajeeb reviewed
All suggestions are considered and changes are made.

2022-09-20 09:46 UTC, atapas commented
> All suggestions are considered and changes are made.

@AmenaNajeeb I do not see the changes though... Have you pushed?

2022-09-20 10:49 UTC, AmenaNajeeb reviewed
Updated File.

![Screenshot (2135)](https://user-images.githubusercontent.com/32102712/191238971-299b1132-926c-4159-ad3b-df40ac1e9fbd.png)
![Screenshot (2136)](https://user-images.githubusercontent.com/32102712/191238981-64e15251-eb33-4106-a973-d816a0c04b03.png)

2022-09-20 10:53 UTC, atapas commented
> Updated File.
> 
> ![Screenshot (2135)](https://user-images.githubusercontent.com/32102712/191238971-299b1132-926c-4159-ad3b-df40ac1e9fbd.png) ![Screenshot (2136)](https://user-images.githubusercontent.com/32102712/191238981-64e15251-eb33-4106-a973-d816a0c04b03.png)

Yes but it is in your forked Repo, you need to push it to UPSTREAM again to get reflected in the PR @AmenaNajeeb

2022-09-20 17:02 UTC, AmenaNajeeb commented
Pushed the Updated File on your Original Repo. 

Please check, Sir.

I referred this link:  https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork

2022-09-21 01:25 UTC, atapas commented
@AmenaNajeeb well, I still don't see your changes in the upstream repo. You can check it here: https://github.com/atapas/markdown-cheatsheet/pull/12/files

Can you please paste all the commands you are trying to push your changes to upstream?

2022-09-21 06:20 UTC, AmenaNajeeb commented
Yes Sir.
The changes that I had done were on my repo in GitHub.
I first opened GitBash and cloned by repo to my local computer.
Then changed the directory path to this cloned repo.
Then..
$git remote add atapas git://github/atapas/markdown-cheatsheet
Then
$git remote -v

2022-09-21 06:21 UTC, AmenaNajeeb reviewed
Line 26 and Lines 426 to 485 are added to explain DropDown.

2022-09-21 08:21 UTC, atapas approved these changes

2022-09-21 08:21 UTC, merged

2022-10-11 09:25 UTC, AmenaNajeeb commented
Pushed the Updated File on your Original Repo.

Please check.

Referred this link:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork


On Tue, Sep 20, 2022, 16:24 Tapas Adhikary ***@***.***> wrote:

> Updated File.
>
> [image: Screenshot (2135)]
> <https://user-images.githubusercontent.com/32102712/191238971-299b1132-926c-4159-ad3b-df40ac1e9fbd.png> [image:
> Screenshot (2136)]
> <https://user-images.githubusercontent.com/32102712/191238981-64e15251-eb33-4106-a973-d816a0c04b03.png>
>
> Yes but it is in your forked Repo, you need to push it to UPSTREAM again
> to get reflected in the PR @AmenaNajeeb <https://github.com/AmenaNajeeb>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/atapas/markdown-cheatsheet/pull/12#issuecomment-1252180845>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHU5SOBSLFJR7VS5XNOIB4DV7GJU7ANCNFSM6AAAAAAQPRKTNA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>