#5 Add Unordered List of Items with a asterisk (*) format
atapas/markdown-cheatsheet pull request #7
Opened 2022-06-11 14:56 UTC by Sachin-chaurasiya

2022-06-11 14:56 UTC, Sachin-chaurasiya commented
@atapas, Please review.

2022-06-11 15:30 UTC, atapas requested changes

2022-06-11 15:30 UTC, atapas commented on README.md
@Sachin-chaurasiya Can we please add a line here explaining the below one is an alternate syntax?

2022-06-11 17:41 UTC, Sachin-chaurasiya commented on README.md
@atapas , Yes, I will add that.

2022-06-12 12:14 UTC, Sachin-chaurasiya commented on README.md
@atapas , I have made the changes, please review.

2022-06-13 03:34 UTC, atapas approved these changes
LGTM

2022-06-13 03:34 UTC, merged